console.log("My first console project");
var first_name = "Aryan";
var last_name = "Mohanty";
var Full_name = first_name.concat(last_name);
console.log (Full_name);
var a = 50;
var b = 20;
var add = a + b;
console.log(add);
var subtract = a - b;
console.log(subtract);
var divide = a / b;
console.log(divide);
var multiply = a * b;
console.log(multiply);